services:
  pppj-music:
    build:
      context: .
    container_name: pppj-music
    ports:
      - 2002:5000
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
    volumes:
      - ./data:/data

volumes:
  data: {}
